export const countries = [
  "Australia",
  "België",
  "Canada",
  "Czech Republic",
  "Chile",
  "Deutschland",
  "España",
  "France",
  "Ireland",
  "Italia",
  "Magyarország",
  "Mexico",
  "Nederland",
  "New Zealand",
  "Österreich",
  "Polska",
  "Portugal",
  "România",
  "Schweiz",
  "Slovensko",
  "United Kingdom",
  "United States",
  "Ελλάδα",
  "מְדִינַת יִשְׂרָאֵל",
];
